# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IF_mean <- function(returns) {
    .Call(`_RPEIF_IF_mean`, returns)
}

IF_SD <- function(returns) {
    .Call(`_RPEIF_IF_SD`, returns)
}

IF_SR <- function(returns, rf) {
    .Call(`_RPEIF_IF_SR`, returns, rf)
}

IF_SoR_mean <- function(returns, rf) {
    .Call(`_RPEIF_IF_SoR_mean`, returns, rf)
}

IF_OmegaRatio <- function(returns, cst) {
    .Call(`_RPEIF_IF_OmegaRatio`, returns, cst)
}

IF_SSD <- function(returns, rf) {
    .Call(`_RPEIF_IF_SSD`, returns, rf)
}

